// vue/day9/project/src/views/VoteMain.vue
<template>
  <main class="mainBox">
    <p>支持人数：{{supnum}} 人</p>
    <p>反对人数：{{oppnum}} 人</p>
    <p>支持比率：{{ratio}}</p>
  </main>
</template>

<script>
export default {
  props: {
    supnum: {
      type: Number,
      default: 0
    },
    oppnum: {
      type: Number,
      default: 0
    }
  },
  computed: {
    ratio() {
      let { supnum, oppnum } = this,
        total = supnum + oppnum;
      return total === 0 ? `--` : `${((supnum / total) * 100).toFixed(2)}%`;
    }
  }
};
</script>

<style lang="less" scoped>
.mainBox {
  margin: 10px auto;

  p {
    line-height: 35px;
    margin: 0;
  }
}
</style>

// react/day5/src/0-属性传递备份/views/VoteMain.jsx
import React from 'react';

function ratio(supNum, oppNum) {
	let total = supNum + oppNum;
	if (total === 0) return '--';
	return (supNum / total * 100).toFixed(2) + '%';
}

export default function VoteMain(props) {
	let { supNum = 0, oppNum = 0 } = props;
	return <main className="voteMain">
		<p>支持数：{supNum}</p>
		<p>反对数：{oppNum}</p>
		<p>支持率：{ratio(supNum, oppNum)}</p>
	</main>;
};
